# SAC Agent Configuration
gamma: 0.99
learning_rate: 0.0003
tau: 0.005  # Soft update coefficient
alpha: 0.2  # Temperature parameter
automatic_entropy_tuning: true
target_update_interval: 1
batch_size: 256
buffer_size: 100000
warmup_steps: 1000

network:
  hidden_dims: [256, 256] 